// 此文件由 scripts/fetch-offline-tiles.js 生成，请勿手改。
// 离线地图的腾讯栅格瓦片（z9 概览 + z10 细节，广东范围）。
import type { ImageSourcePropType } from 'react-native';

// POI 投影基准网格（取 z9，与渲染用的瓦片级别无关）。
export const OFFLINE_TILE_GRID = {
  z: 9,
  xMin: 414,
  yMin: 220,
  cols: 9,
  rows: 5,
  tileSize: 256,
} as const;

export interface OfflineTileLevel {
  cols: number;
  rows: number;
  tiles: ImageSourcePropType[][]; // [row][col]
}

// 多级瓦片，按缩放从概览到细节。
export const OFFLINE_TILE_LEVELS: OfflineTileLevel[] = [
  {
    cols: 9,
    rows: 5,
    tiles: [
      [require('../assets/offline-map/z9-0-0.jpg'), require('../assets/offline-map/z9-1-0.jpg'), require('../assets/offline-map/z9-2-0.jpg'), require('../assets/offline-map/z9-3-0.jpg'), require('../assets/offline-map/z9-4-0.jpg'), require('../assets/offline-map/z9-5-0.jpg'), require('../assets/offline-map/z9-6-0.jpg'), require('../assets/offline-map/z9-7-0.jpg'), require('../assets/offline-map/z9-8-0.jpg')],
      [require('../assets/offline-map/z9-0-1.jpg'), require('../assets/offline-map/z9-1-1.jpg'), require('../assets/offline-map/z9-2-1.jpg'), require('../assets/offline-map/z9-3-1.jpg'), require('../assets/offline-map/z9-4-1.jpg'), require('../assets/offline-map/z9-5-1.jpg'), require('../assets/offline-map/z9-6-1.jpg'), require('../assets/offline-map/z9-7-1.jpg'), require('../assets/offline-map/z9-8-1.jpg')],
      [require('../assets/offline-map/z9-0-2.jpg'), require('../assets/offline-map/z9-1-2.jpg'), require('../assets/offline-map/z9-2-2.jpg'), require('../assets/offline-map/z9-3-2.jpg'), require('../assets/offline-map/z9-4-2.jpg'), require('../assets/offline-map/z9-5-2.jpg'), require('../assets/offline-map/z9-6-2.jpg'), require('../assets/offline-map/z9-7-2.jpg'), require('../assets/offline-map/z9-8-2.jpg')],
      [require('../assets/offline-map/z9-0-3.jpg'), require('../assets/offline-map/z9-1-3.jpg'), require('../assets/offline-map/z9-2-3.jpg'), require('../assets/offline-map/z9-3-3.jpg'), require('../assets/offline-map/z9-4-3.jpg'), require('../assets/offline-map/z9-5-3.jpg'), require('../assets/offline-map/z9-6-3.jpg'), require('../assets/offline-map/z9-7-3.jpg'), require('../assets/offline-map/z9-8-3.jpg')],
      [require('../assets/offline-map/z9-0-4.jpg'), require('../assets/offline-map/z9-1-4.jpg'), require('../assets/offline-map/z9-2-4.jpg'), require('../assets/offline-map/z9-3-4.jpg'), require('../assets/offline-map/z9-4-4.jpg'), require('../assets/offline-map/z9-5-4.jpg'), require('../assets/offline-map/z9-6-4.jpg'), require('../assets/offline-map/z9-7-4.jpg'), require('../assets/offline-map/z9-8-4.jpg')],
    ],
  },
  {
    cols: 18,
    rows: 10,
    tiles: [
      [require('../assets/offline-map/z10-0-0.jpg'), require('../assets/offline-map/z10-1-0.jpg'), require('../assets/offline-map/z10-2-0.jpg'), require('../assets/offline-map/z10-3-0.jpg'), require('../assets/offline-map/z10-4-0.jpg'), require('../assets/offline-map/z10-5-0.jpg'), require('../assets/offline-map/z10-6-0.jpg'), require('../assets/offline-map/z10-7-0.jpg'), require('../assets/offline-map/z10-8-0.jpg'), require('../assets/offline-map/z10-9-0.jpg'), require('../assets/offline-map/z10-10-0.jpg'), require('../assets/offline-map/z10-11-0.jpg'), require('../assets/offline-map/z10-12-0.jpg'), require('../assets/offline-map/z10-13-0.jpg'), require('../assets/offline-map/z10-14-0.jpg'), require('../assets/offline-map/z10-15-0.jpg'), require('../assets/offline-map/z10-16-0.jpg'), require('../assets/offline-map/z10-17-0.jpg')],
      [require('../assets/offline-map/z10-0-1.jpg'), require('../assets/offline-map/z10-1-1.jpg'), require('../assets/offline-map/z10-2-1.jpg'), require('../assets/offline-map/z10-3-1.jpg'), require('../assets/offline-map/z10-4-1.jpg'), require('../assets/offline-map/z10-5-1.jpg'), require('../assets/offline-map/z10-6-1.jpg'), require('../assets/offline-map/z10-7-1.jpg'), require('../assets/offline-map/z10-8-1.jpg'), require('../assets/offline-map/z10-9-1.jpg'), require('../assets/offline-map/z10-10-1.jpg'), require('../assets/offline-map/z10-11-1.jpg'), require('../assets/offline-map/z10-12-1.jpg'), require('../assets/offline-map/z10-13-1.jpg'), require('../assets/offline-map/z10-14-1.jpg'), require('../assets/offline-map/z10-15-1.jpg'), require('../assets/offline-map/z10-16-1.jpg'), require('../assets/offline-map/z10-17-1.jpg')],
      [require('../assets/offline-map/z10-0-2.jpg'), require('../assets/offline-map/z10-1-2.jpg'), require('../assets/offline-map/z10-2-2.jpg'), require('../assets/offline-map/z10-3-2.jpg'), require('../assets/offline-map/z10-4-2.jpg'), require('../assets/offline-map/z10-5-2.jpg'), require('../assets/offline-map/z10-6-2.jpg'), require('../assets/offline-map/z10-7-2.jpg'), require('../assets/offline-map/z10-8-2.jpg'), require('../assets/offline-map/z10-9-2.jpg'), require('../assets/offline-map/z10-10-2.jpg'), require('../assets/offline-map/z10-11-2.jpg'), require('../assets/offline-map/z10-12-2.jpg'), require('../assets/offline-map/z10-13-2.jpg'), require('../assets/offline-map/z10-14-2.jpg'), require('../assets/offline-map/z10-15-2.jpg'), require('../assets/offline-map/z10-16-2.jpg'), require('../assets/offline-map/z10-17-2.jpg')],
      [require('../assets/offline-map/z10-0-3.jpg'), require('../assets/offline-map/z10-1-3.jpg'), require('../assets/offline-map/z10-2-3.jpg'), require('../assets/offline-map/z10-3-3.jpg'), require('../assets/offline-map/z10-4-3.jpg'), require('../assets/offline-map/z10-5-3.jpg'), require('../assets/offline-map/z10-6-3.jpg'), require('../assets/offline-map/z10-7-3.jpg'), require('../assets/offline-map/z10-8-3.jpg'), require('../assets/offline-map/z10-9-3.jpg'), require('../assets/offline-map/z10-10-3.jpg'), require('../assets/offline-map/z10-11-3.jpg'), require('../assets/offline-map/z10-12-3.jpg'), require('../assets/offline-map/z10-13-3.jpg'), require('../assets/offline-map/z10-14-3.jpg'), require('../assets/offline-map/z10-15-3.jpg'), require('../assets/offline-map/z10-16-3.jpg'), require('../assets/offline-map/z10-17-3.jpg')],
      [require('../assets/offline-map/z10-0-4.jpg'), require('../assets/offline-map/z10-1-4.jpg'), require('../assets/offline-map/z10-2-4.jpg'), require('../assets/offline-map/z10-3-4.jpg'), require('../assets/offline-map/z10-4-4.jpg'), require('../assets/offline-map/z10-5-4.jpg'), require('../assets/offline-map/z10-6-4.jpg'), require('../assets/offline-map/z10-7-4.jpg'), require('../assets/offline-map/z10-8-4.jpg'), require('../assets/offline-map/z10-9-4.jpg'), require('../assets/offline-map/z10-10-4.jpg'), require('../assets/offline-map/z10-11-4.jpg'), require('../assets/offline-map/z10-12-4.jpg'), require('../assets/offline-map/z10-13-4.jpg'), require('../assets/offline-map/z10-14-4.jpg'), require('../assets/offline-map/z10-15-4.jpg'), require('../assets/offline-map/z10-16-4.jpg'), require('../assets/offline-map/z10-17-4.jpg')],
      [require('../assets/offline-map/z10-0-5.jpg'), require('../assets/offline-map/z10-1-5.jpg'), require('../assets/offline-map/z10-2-5.jpg'), require('../assets/offline-map/z10-3-5.jpg'), require('../assets/offline-map/z10-4-5.jpg'), require('../assets/offline-map/z10-5-5.jpg'), require('../assets/offline-map/z10-6-5.jpg'), require('../assets/offline-map/z10-7-5.jpg'), require('../assets/offline-map/z10-8-5.jpg'), require('../assets/offline-map/z10-9-5.jpg'), require('../assets/offline-map/z10-10-5.jpg'), require('../assets/offline-map/z10-11-5.jpg'), require('../assets/offline-map/z10-12-5.jpg'), require('../assets/offline-map/z10-13-5.jpg'), require('../assets/offline-map/z10-14-5.jpg'), require('../assets/offline-map/z10-15-5.jpg'), require('../assets/offline-map/z10-16-5.jpg'), require('../assets/offline-map/z10-17-5.jpg')],
      [require('../assets/offline-map/z10-0-6.jpg'), require('../assets/offline-map/z10-1-6.jpg'), require('../assets/offline-map/z10-2-6.jpg'), require('../assets/offline-map/z10-3-6.jpg'), require('../assets/offline-map/z10-4-6.jpg'), require('../assets/offline-map/z10-5-6.jpg'), require('../assets/offline-map/z10-6-6.jpg'), require('../assets/offline-map/z10-7-6.jpg'), require('../assets/offline-map/z10-8-6.jpg'), require('../assets/offline-map/z10-9-6.jpg'), require('../assets/offline-map/z10-10-6.jpg'), require('../assets/offline-map/z10-11-6.jpg'), require('../assets/offline-map/z10-12-6.jpg'), require('../assets/offline-map/z10-13-6.jpg'), require('../assets/offline-map/z10-14-6.jpg'), require('../assets/offline-map/z10-15-6.jpg'), require('../assets/offline-map/z10-16-6.jpg'), require('../assets/offline-map/z10-17-6.jpg')],
      [require('../assets/offline-map/z10-0-7.jpg'), require('../assets/offline-map/z10-1-7.jpg'), require('../assets/offline-map/z10-2-7.jpg'), require('../assets/offline-map/z10-3-7.jpg'), require('../assets/offline-map/z10-4-7.jpg'), require('../assets/offline-map/z10-5-7.jpg'), require('../assets/offline-map/z10-6-7.jpg'), require('../assets/offline-map/z10-7-7.jpg'), require('../assets/offline-map/z10-8-7.jpg'), require('../assets/offline-map/z10-9-7.jpg'), require('../assets/offline-map/z10-10-7.jpg'), require('../assets/offline-map/z10-11-7.jpg'), require('../assets/offline-map/z10-12-7.jpg'), require('../assets/offline-map/z10-13-7.jpg'), require('../assets/offline-map/z10-14-7.jpg'), require('../assets/offline-map/z10-15-7.jpg'), require('../assets/offline-map/z10-16-7.jpg'), require('../assets/offline-map/z10-17-7.jpg')],
      [require('../assets/offline-map/z10-0-8.jpg'), require('../assets/offline-map/z10-1-8.jpg'), require('../assets/offline-map/z10-2-8.jpg'), require('../assets/offline-map/z10-3-8.jpg'), require('../assets/offline-map/z10-4-8.jpg'), require('../assets/offline-map/z10-5-8.jpg'), require('../assets/offline-map/z10-6-8.jpg'), require('../assets/offline-map/z10-7-8.jpg'), require('../assets/offline-map/z10-8-8.jpg'), require('../assets/offline-map/z10-9-8.jpg'), require('../assets/offline-map/z10-10-8.jpg'), require('../assets/offline-map/z10-11-8.jpg'), require('../assets/offline-map/z10-12-8.jpg'), require('../assets/offline-map/z10-13-8.jpg'), require('../assets/offline-map/z10-14-8.jpg'), require('../assets/offline-map/z10-15-8.jpg'), require('../assets/offline-map/z10-16-8.jpg'), require('../assets/offline-map/z10-17-8.jpg')],
      [require('../assets/offline-map/z10-0-9.jpg'), require('../assets/offline-map/z10-1-9.jpg'), require('../assets/offline-map/z10-2-9.jpg'), require('../assets/offline-map/z10-3-9.jpg'), require('../assets/offline-map/z10-4-9.jpg'), require('../assets/offline-map/z10-5-9.jpg'), require('../assets/offline-map/z10-6-9.jpg'), require('../assets/offline-map/z10-7-9.jpg'), require('../assets/offline-map/z10-8-9.jpg'), require('../assets/offline-map/z10-9-9.jpg'), require('../assets/offline-map/z10-10-9.jpg'), require('../assets/offline-map/z10-11-9.jpg'), require('../assets/offline-map/z10-12-9.jpg'), require('../assets/offline-map/z10-13-9.jpg'), require('../assets/offline-map/z10-14-9.jpg'), require('../assets/offline-map/z10-15-9.jpg'), require('../assets/offline-map/z10-16-9.jpg'), require('../assets/offline-map/z10-17-9.jpg')],
    ],
  },
];
